package com.dometic.L2.qa.Pages;

public class Constant_settings {
    // --------------Accessibility_id-------------------//
    public static final String Settings_Back_Button_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Settings_languageContainer_access_id="com.dometicapp:id/setting-languageContainer";
    public static final String Settings_versionContainer_access_id="com.dometicapp:id/setting-versionContainer";
    public static final String Settings_language_text_access_id="com.dometicapp:id/setting-languageText";
    public static final String Settings_language_text_expected="Sprachen";
    public static final String Settings_language_Spanish_text_expected="Idioma";
    public static final String Settings_temperature_Spanish_text_expected="Unidad de temperatura";
    public static final String Settings_version_Spanish_text_expected="Versión 1.3";
    public static final String Settings_logout_Spanish_text_expected="Cerrar sesión";
    public static final String Settings_language_French_text_expected="Langue";
    public static final String Settings_temperature_French_text_expected="Unité de température";
    public static final String Settings_version_French_text_expected="Version 1.3";
    public static final String Settings_logout_French_text_expected="Déconnexion";
    public static final String Settings_language_selectedName_access_id="com.dometicapp:id/setting-selectedLanguage";
    public static final String Settings_languages_navigation_button_access_id="com.dometicapp:id/setting-languageiconCollapse";
    public static final String Settings_Language_English_tick_access_id="com.dometicapp:id/language-iconTickEnglish";
    public static final String Settings_language_German_access_id="com.dometicapp:id/language-germanText";
    public static final String Settings_Language_German_tick_access_id="com.dometicapp:id/language-iconTickGerman";
    public static final String Settings_Temperature_text_access_id="com.dometicapp:id/setting-temperatureContainer";
    public static final String Settings_Temperature_text_expected="Temperatureinheit";
    public static final String Settings_version_text_access_id="com.dometicapp:id/setting-versionText";
    public static final String Settings_logout_text_access_id="com.dometicapp:id/setting-logOutText";
    public static final String Settings_logout_expected="Abmelden";
    public static final String Settings_fahrenheit_access_id="com.dometicapp:id/setting-fahrenheitText";
    public static final String Settings_Temperature_unit_access_id="com.dometicapp:id/setting-temperatureButtons";
    public static final String Settings_Zone_Management_expected="Zone Management";
    public static final String Settings_Zone_Management_ALL_ZONES_text="ALL ZONES";
    public static final String Settings_Zone_Management_edit_text="Edit";
    public static final String Settings_Zone_Management_LimitedZones_text="Limited to 4 Zones only";
    public static final String Settings_Zone_Management_addZoneIcon_access_id="com.dometicapp:id/zoneManagement-addZoneIcon";
    public static final String Settings_Zone_Management_addZoneIcon_Select_button_access_id="com.dometicapp:id/ZoneNumber-selectButton";
    public static final String Settings_Zone_Management_addZoneIcon_Select_text_access_id="com.dometicapp:id/ZoneNumber-selectZoneText";
    public static final String Settings_Zone_Management_Zone_Name_can_not_be_empty_text="Zone Name can not be empty";
    public static final String Settings_Zone_Management_10_character_text="10/10 character";
    public static final String Settings_Zone_Management_value="Living Room";
    public static final String Settings_Zone_Management_Living_Room="LivingRoom";
    public static final String Settings_Zone_Management_NewZone_Room="StudyRoom";
    public static final String Settings_Zone_Management_deleteZoneAlert_cancelButton_access_id="com.dometicapp:id/zoneManagement-deleteZoneAlert-saveButton";
    public static final String Settings_Zone_Management_deleteZoneAlert_YES_DELETE_ITButton_access_id="com.dometicapp:id/zoneManagement-deleteZoneAlert-cancelButton";
    public static final String Settings_Zone_Management_new_Zone_access_id="com.dometicapp:id/ZoneNumber-dialog-undefined";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_saveButton_access_id="com.dometicapp:id/ZoneNumber-dialog-saveButton";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_cancelButton_access_id="com.dometicapp:id/ZoneNumber-dialog-cancelButton";
    public static final String Device_Management_access_id = "com.dometicapp:id/sidemenu-deviceMangagement-text";
    public static final String Device_Management_Device_name_access_id = "com.dometicapp:id/DeviceManagement-deviceName";
    public static final String Device_Management_header_access_id = "com.dometicapp:id/header-TitleText";
    public static final String Device_Management_back_button_access_id = "com.dometicapp:id/header-leftButtonImage";
    public static final String Device_Management_image_access_id = "com.dometicapp:id/deviceManagement-deviceImage";
    public static final String Device_Management_page_Device_name_access_id = "com.dometicapp:id/deviceManagement-deviceName";
    public static final String Device_Management_Vessel_information_text_access_id = "com.dometicapp:id/deviceManagement-vesseltitleLabel";
    public static final String Device_Management_Name_text_access_id = "com.dometicapp:id/deviceManagement-vesselNameLabel";
    public static final String Device_Management_Name_access_id = "com.dometicapp:id/deviceManagement-vesselNameValue";
    public static final String Device_Management_MAC_address_text_access_id = "com.dometicapp:id/deviceManagement-hullIdLabel";
    public static final String Device_Management_MAC_address_access_id = "com.dometicapp:id/deviceManagement-hullIdValue";
    public static final String Device_Management_Edit_vessel_text_access_id = "com.dometicapp:id/deviceManagement-editVessel-cardTitle";
    public static final String Device_Management_Edit_vessel_navigation_access_id = "com.dometicapp:id/deviceManagement-editVessel-cardIcon";

    public static final String Device_Management_Edit_vessel_header_access_id = "com.dometicapp:id/header-TitleText";
    public static final String Device_Management_Edit_vessel_image_access_id = "com.dometicapp:id/deviceManagement-deviceImage";
    public static final String Device_Management_Edit_vessel_name_text_access_id = "com.dometicapp:id/editVessel-vesselNameLabel";
    public static final String Device_Management_Edit_vessel_name_access_id = "com.dometicapp:id/editVessel-vesselNameValue";
    public static final String Device_Management_Edit_vessel_MAC_address_text_access_id = "com.dometicapp:id/editVessel-hullIdLabel";
    public static final String Device_Management_Edit_vessel_MAC_address_access_id = "com.dometicapp:id/editVessel-hullIdValue";
    public static final String Device_Management_Edit_vessel_Save_text_access_id = "com.dometicapp:id/editVessel-saveButtonText";
    public static final String Device_Management_Edit_vessel_Save_button_access_id = "com.dometicapp:id/editVessel-saveButton";
    public static final String Device_Management_1st_device_name_access_id = "com.dometicapp:id/DeviceManagement-deviceName";
    public static final String Device_Management_Advanced_text_access_id = "com.dometicapp:id/deviceManagement-advancedTitleText";
    public static final String Device_Management_Check_updates_text_access_id = "com.dometicapp:id/deviceManagement-checkForUpdates-cardTitle";
    public static final String Device_Management_Check_updates_navigation_access_id = "com.dometicapp:id/deviceManagement-checkForUpdates-cardIcon";
    public static final String Device_Management_Unregister_Delete_offboard_text_access_id = "com.dometicapp:id/deviceManagement-unregisterDelete-cardTitle";
    public static final String Device_Management_Unregister_Delete_offboard_navigation_access_id = "com.dometicapp:id/deviceManagement-unregisterDelete-cardIcon";
    public static final String Settings_Edit_profile_Header_text_accessid="com.dometicapp:id/header-TitleText";
    public static final String Settings_Edit_profile_CloseButton_accessid="com.dometicapp:id/header-leftButtonImage";
    public static final String Settings_Edit_profile_firstname_text_accessid="com.dometicapp:id/editProfile-firstNameLabel";
    public static final String Settings_Edit_profile_firstname_value_accessid="com.dometicapp:id/editProfile-firstNNameValue";
    public static final String Settings_Edit_profile_lastname_text_accessid="com.dometicapp:id/editProfile-lastameLabel";
    public static final String Settings_Edit_profile_lastname_value_accessid="com.dometicapp:id/editProfile-lastNameValue";
    public static final String Settings_Edit_profile_primaryMobile_text_accessid="com.dometicapp:id/editProfile-phoneLabel";
    public static final String Settings_Edit_profile_primaryMobile_value_accessid="com.dometicapp:id/editProfile-phoneValue";
    public static final String Settings_Edit_profile_address_text_accessid="com.dometicapp:id/editProfile-addressLabel";
    public static final String Settings_Edit_profile_address_value_accessid="com.dometicapp:id/editProfile-addressValue";
    public static final String Settings_Edit_profile_photo_accessid="com.dometicapp:id/editProfile-photo";
    public static final String Settings_Edit_profile_emailvalue_accessid="com.dometicapp:id/editProfile-emailValue";
    public static final String Settings_Edit_profile_saveButton_accessid="com.dometicapp:id/editProfile-saveButtonText";
    public static final String Settings_Edit_profile_ok_button_xpath="//*[@text='OK']";
    public static final String Settings_Subscription_header_accessid="com.dometicapp:id/header-TitleText";
    public static final String Settings_Subscription_header_text="SUBSCRIPTIONS";
    //-----------Account Settings--------------------//
    public static final String Settings_ViewEditAccount_accessid="com.dometicapp:id/sidemenu-viewEditButtonText";
    public static final String Settings_AccountSettings_header_accessid="com.dometicapp:id/header-TitleText";
    public static final String Settings_AccountSettings_profilePhoto_accessid="com.dometicapp:id/userSettings-profilePhoto";
    public static final String Settings_AccountSettings_userName_accessid="com.dometicapp:id/userSettings-userName";
    public static final String Settings_AccountSettings_user_email_accessid="com.dometicapp:id/userSettings-userEmail";
    public static final String Settings_AccountSettings_profile_Text_accessid="com.dometicapp:id/userSettings-profile-cardTitle";
    public static final String Settings_AccountSettings_profile_cardicon_accessid="com.dometicapp:id/userSettings-profile-cardIcon";
    public static final String Settings_AccountSettings_Subscription_text_accessid="com.dometicapp:id/userSettings-subscriptions-cardTitle";
    public static final String Settings_AccountSettings_Subscription_cardicon_accessid="com.dometicapp:id/userSettings-subscriptions-cardIcon";

    //--------------profile page------------//
    public static final String Settings_profile_header_accessid="com.dometicapp:id/header-TitleText";
    public static final String Settings_profile_Persolnal_information_accessid="com.dometicapp:id/userProfile-personalInfoText";
    public static final String Settings_profile_Name_label_accessid="com.dometicapp:id/userProfile-nameLabel";
    public static final String Settings_profile_namevalues_accessid="com.dometicapp:id/userProfile-nameValue";
    public static final String Settings_profile_email_label_accessid="com.dometicapp:id/userProfile-emailLabel";
    public static final String Settings_profile_emailvalues_accessid ="com.dometicapp:id/userProfile-emailValue";
    public static final String Settings_profile_mobile_label_accessid="com.dometicapp:id/userProfile-phoneLabel";
    public static final String Settings_profile_mobilevalues_accessid="com.dometicapp:id/userProfile-phoneValue";
    public static final String Settings_profile_address_label_accessid="com.dometicapp:id/userProfile-addressLabel";
    public static final String Settings_profile_addressvalues_accessid ="com.dometicapp:id/userProfile-addressValue";
    public static final String Settings_profile_Editprofile_label_accessid="com.dometicapp:id/userProfile-EditProfileButton-cardTitle";
    public static final String Settings_profile_Editprofile_cardicon_accessid ="com.dometicapp:id/userProfile-EditProfileButton-cardIcon";
    public static final String Settings_profile_Security_text_accessid="com.dometicapp:id/userProfile-securityText";
    public static final String Settings_profile_Password_text_accessid="com.dometicapp:id/userProfile-resetPasswordText";
    public static final String Settings_profile_Renew_text_accessid="com.dometicapp:id/userProfile-renew-cardTitle";
    public static final String Settings_profile_renew_cardicon_accessid ="com.dometicapp:id/userProfile-renew-cardIcon";


    public static final String Settings_App_settings_App_Setting_name_on_settings_page="com.dometicapp:id/sidemenu-appSettings-text";
    public static final String Settings_App_settings_App_setting_header_tile_text_access_id="com.dometicapp:id/header-TitleText";
    public static final String Settings_App_settings_App_setting_page_back_button_icon_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Settings_App_settings_App_language_text_access_id="com.dometicapp:id/setting-languageText";
    public static final String Settings_App_settings_language_text_collapse_button_access_id="com.dometicapp:id/setting-languageText";
    public static final String Settings_App_settings_Temperature_text_access_id="com.dometicapp:id/setting-temperatureContainer";
    public static final String Settings_App_settings_Temperature_celcius_text_access_id="com.dometicapp:id/setting-celsiusText";
    public static final String Settings_App_settings_Temperature_fahrenheit_text_access_id="com.dometicapp:id/setting-fahrenheitText";
    public static final String Settings_App_settings_App_version_access_id="com.dometicapp:id/setting-versionText";
    public static final String Settings_App_settings_Language_header_text_access_id="com.dometicapp:id/header-TitleText";
    public static final String Settings_App_settings_Language_page_back_button_icon_access_id="com.dometicapp:id/tiles-backImage";
    public static final String Settings_App_settings_english_language_text_access_id="com.dometicapp:id/language-english-cardTitle";
    public static final String Settings_App_settings_spanish_language_text_access_id="com.dometicapp:id/language-spanish-cardTitle";
    public static final String Settings_App_settings_french_language_text_access_id="com.dometicapp:id/language-french-cardTitle";
    public static final String Settings_App_settings_german_language_text_access_id="com.dometicapp:id/language-german-cardTitle";
    public static final String Climate_main_tile_Celcius_unit_access_id="com.dometicapp:id/tile-climate-cardUnitText-0";
    public static final String Climate_main_tile_Fharanite_unit_access_id="com.dometicapp:id/tile-climate-cardUnitText-1";
    public static final String Climate_main_tile_inside_temp="com.dometicapp:id/climate-insideTemp";

    public static final String Settings_App_setting_header_text_expected="APP SETTINGS";
    public static final String Settings_App_setting_language_text_expected="Language";
    public static final String Settings_App_setting_temperature_text_expected="Temperature";
    public static final String Settings_App_setting_app_version_text_expected="App version";
    public static final String Settings_App_setting_Language_page_header_text_expected="LANGUAGE";
    public static final String Settings_App_setting_Language_page_English_text_expected="English";
    public static final String Settings_App_setting_Language_page_Spanish_text_expected="Spanish(US)";
    public static final String Settings_App_setting_Language_page_French_text_expected="French";
    public static final String Settings_App_setting_Language_page_German_text_expected="German";

    //-----------Account Settings Data--------------------//
    public static final String Settings_AccountSettings_header_text="ACCOUNT SETTINGS";
    public static final String Settings_AccountSettings_profile_text="Profile";
    public static final String Settings_AccountSettings_Subscription_text="Subscriptions";
    public static final String Settings_profile_header="PROFILE";
    public static final String Settings_profile_Persolnal_information="PERSONAL INFORMATION";
    public static final String Settings_profile_Name_label="Name";
    public static final String Settings_profile_email_label="E-mail";
    public static final String Settings_profile_mobile_label="Mobile";
    public static final String Settings_profile_address_label="Address";
    public static final String Settings_profile_Editprofile_label="Edit Profile";
    public static final String Settings_profile_Security_text="SECURITY";
    public static final String Settings_profile_Password_text="Password";
    public static final String Settings_profile_Renew_text="Renew";

    //-------------------Needed Accessibility Id-----------------//
    public static final String Settings_Language_Page_title_access_id="";
    public static final String Settings_language_Back_button_access_id="";
    public static final String Settings_Language_English_access_id="";
    public static final String Settings_back_button_access_id="";
    public static final String Settings_page_title_access_id="";
    public static final String Settings_temperature_unit_C_access_id="";
    public static final String Settings_temperature_unit_F_access_id="";

    // ----------------------xpath-----------------------------//
    public static final String Settings_text_xpath="(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage'])[1]";
    public static final String Settings_Language_select_xpath="(//*[@content-desc='com.dometicapp:id/setting-languageContainer'])[1]";
    public static final String Settings_Temperature_unit_xpath="(//*[@class='android.view.ViewGroup'])[17]";
    public static final String Settings_Upgrade_Firmware_xpath="(//*[@content-desc='com.dometicapp:id/setting-languageContainer'])[2]";
    public static final String Settings_Version_xpath="//*[@content-desc='com.dometicapp:id/setting-versionContainer']";
    public static final String Settings_Logout_xpath="//android.view.ViewGroup[@content-desc='com.dometicapp:id/setting-logOutContainer']/android.view.ViewGroup";
    public static final String Settings_Language_Page_title_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView";
    public static final String Settings_language_Back_button_xpath="//android.widget.Button[@content-desc=\" , back\"]/android.view.ViewGroup/android.widget.ImageView";
    public static final String Settings_Language_English_xpath="//android.widget.TextView[@content-desc=\"com.dometicapp:id/language-englishContainer\"]";
    public static final String Settings_back_button_xpath="/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[1]";
    public static final String Settings_page_title_xpath= "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.FrameLayout/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup/android.view.ViewGroup[2]/android.widget.TextView";
    public static final String Settings_temperature_unit_C_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/setting-temperatureButtons\"]/android.view.ViewGroup[1]/android.view.ViewGroup/android.widget.TextView";
    public static final String Settings_temperature_unit_F_xpath="//android.view.ViewGroup[@content-desc=\"com.dometicapp:id/setting-temperatureButtons\"]/android.view.ViewGroup[2]/android.view.ViewGroup/android.widget.TextView\n";
    public static final String Settings_language_Spanish_xpath="//*[@text='Spanish (US)']";
    public static final String Settings_language_French_xpath="//*[@text='French']";
    public static final String Settings_language_xpath="(//*[@content-desc='com.dometicapp:id/setting-languageText'])[1]";
    public static final String Settings_Zone_Management_xpath="(//*[@content-desc='com.dometicapp:id/setting-scrollView']//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_edit_xpath="(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage']//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_LimitedZones_xpath="(//*[@content-desc='com.dometicapp:id/setting-selectedLanguage']//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_Rename_xpath="(//*[@content-desc='com.dometicapp:id/zoneManagement-flatList']//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_Rename_value_xpath="//android.widget.EditText[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]";
    public static final String Settings_Zone_Management_Zone_Name_can_not_be_empty_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[1]";
    public static final String Settings_Zone_Management_SAVE_Button_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_CANCEL_Button_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-dialog-')]//following::android.widget.TextView)[2]";
    public static final String Settings_Zone_Management_flatListItem_xpath="(//*[contains(@content-desc,'com.dometicapp:id/zoneManagement-flatListItem-')]//following::android.view.ViewGroup)[2]";
    public static final String Settings_Zone_Management_deleteZoneAlert_description_xpath="//*[@content-desc='com.dometicapp:id/zoneManagement-deleteZoneAlert-description']";
    public static final String Settings_Zone_Management_deleteZone_xpath="//*[@text='YES, DELETE IT']";
    public static final String Settings_Zone_Management_addZoneIcon_Select_button_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-selectButton']";
    public static final String Settings_Zone_Management_new_Zone_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-undefined']";
    public static final String Settings_Zone_Management_Zone_name_already_present_xpath="//*[@text='Zone name already present']";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_saveButton_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-saveButton']";
    public static final String Settings_Zone_Management_ZoneNumber_dialog_cancelButton_xpath="//*[@content-desc='com.dometicapp:id/ZoneNumber-dialog-cancelButton']";
    public static final String Device_Management_xpath = "//*[@content-desc=\"com.dometicapp:id/sidemenu-deviceMangagement-button\"]";
    public static final String Device_Management_Edit_vessel_header_xpath = "//*[@content-desc=\"com.dometicapp:id/header-TitleText\"]\n";
    public static final String Device_Management_Edit_vessel_close_button_xpath = "//*[@content-desc=\"com.dometicapp:id/header-rightButton\"]/android.widget.TextView";

    // ----------------------Data-----------------------------//
    public static final String Device_Management_header_text = "DEVICE MANAGEMENT";
    public static final String Vessel_information_text = "VESSEL INFORMATION";
    public static final String Name_text = "Name";
    public static final String MAC_address_text = "MAC Address";
    public static final String Edit_vessel_text = "Edit vessel";
    public static final String Edit_vessel_header_text = "EDIT VESSEL";
    public static final String Edit_vessel_name_text = "Name";
    public static final String Edit_vessel_MAC_address_text = "Mac Address";
    public static final String Save_text = "Save";
    public static final String Advanced_text = "ADVANCED";
    public static final String Check_updates_text = "Check updates";
    public static final String Unregister_Offboard_Delete_text = "Unregister/Delete/Offboard";

    //----------------Edit Profile Data--------------//
    public static final String Settings_Edit_profile_Header_text="EDIT PROFILE";
    public static final String Settings_Edit_profile_firstname_text="First name";
    public static final String Settings_Edit_profile_lastname_text="Last name";
    public static final String Settings_Edit_profile_primaryMobile_text="Primary mobile";
    public static final String Settings_Edit_profile_address_text="Address";
    public static final String editProfile_firstNameValue="RAMESH";
    public static final String editProfile_lastameValue="BABU";
    public static final String editProfile_firstNameValue_SpecialCharacter="!@#$%^&*()_+";
    public static final String editProfile_lastameValue_SpecialCharacter="+_)(*&^%$#@!";
    public static final String grinning_face_with_smiling_eyes = new String(Character.toChars(0x1F601));
    public static final String face_with_tears_of_joy = new String(Character.toChars(0x1F602));
    public static final String smiling_face_with_open_mouth_and_cold_sweat = new String(Character.toChars(0x1F605));
    public static final String smiling_face_with_open_mouth_and_tightly_closed_eyes = new String(Character.toChars(0x1F606));
    public static final String winking_face = new String(Character.toChars(0x1F609));
    public static final String editProfile_phoneValue="+919003034122";
    public static final String editProfile_addressValue="CHENNAI";
    public static final String editProfile_addressValue_SpecialCharacter="!@#$%^&*()_+";
    public static final String Device_name_New_data = "Test12345DevicenamecheckL2Usertest@123byDOM";
    public static final String Device_name_valid_data = "USLTV";
    public static final String Device_name_invalid_data = "%$%***(#@%^&%";
}
